### ISSUE TITLE
Usage of ModernHttpClient

### ISSUE THREAD

**Issue by simondebaecke** [FubarDevelopment/restsharp.portable#1]
Hi !

I'm relatively new to C# development and I don't know if my issue is relevant but as I also have a few remarks/questions, I wanted to ask :
- Would it not be worth using https://github.com/paulcbetts/ModernHttpClient internally ?
- It's not possible to use (error 404) your RestClient with a BaseUrl that doesn't have a trailing "/" (the Resource from RestRequest starts directly with "/").
- I use this PCL with Xamarin and I noticed one strange inconvenience due to the Microsoft.Bcl.Build package dependency : I'm not able to use typeof(MyClass).GetTypeInfo().Assembly anymore ... Do you have any idea to get around this problem ?

Thx in advance for your help ! =)

**Comment by GabLeRoux** [comment]
Thanks for answering this, I was using restsharp.portable before Unified-API's Xamarin change and I needed to move to `ModernHttpClient` to support most recent devices. Following your instructions, I simply wrote this and it worked just fine on `arm64` :)

```c#
using ModernHttpClient;
using RestSharp.Portable.HttpClientImpl;
using System.Net.Http;
using RestSharp.Portable;

namespace MyApp.Common
{
	public class ModernHttpClientFactory : DefaultHttpClientFactory
	{
		protected override HttpMessageHandler CreateMessageHandler (IRestClient client, IRestRequest request)
		{
			return new NativeMessageHandler ();
		}
	}
}
```
