### ISSUE TITLE
Creating and disposing http clients on each request?

### ISSUE THREAD

**Issue by ashic** [FubarDevelopment/restsharp.portable#11]
Is seems the RestClient class is creating and disposing http clients for each request. This seems to be a bad practice: http://stackoverflow.com/questions/18976042/httpclientfactory-create-vs-new-httpclient . When integrating with other clients that expect long lived instances, this is causing us some problems. Is this by design? Is there a workaround? Maintaining a singleton in a custom factory doesn't work either as clients are expected to get created with a request message:

```
var httpClient = HttpClientFactory.CreateClient(this, request)

```

**Comment by fubar-coder** [comment]
It's (currently) by design, but I already thought about a change regarding this behavior. May I ask what the problem is that you've encountered? Maybe I can help you with this problem when you can provide a small test application?

**Comment by ashic** [comment]
As an example, we're trying to use Cache Cow with RestSharp.Portable. It seems that if an Accept header is added, the first request uses uncached values, but subsequent requests from the same httpclient does use the cache. However, since each http request is creating a new client, this becomes a problem.

Another example is using Cache Cow's in memory cache. Creating a new client every request means the cache of the previous client isn't used. Supporting this scenario would be awesome as we'd get automatic caching with Cache Cow without having to add any caching complexity to Restsharp.Portable.

**Comment by fubar-coder** [comment]
I see what you mean. I'll take a look and try to improve the HttpClient usage.

**Comment by ashic** [comment]
Awesome...looking foreward to it. I'll look at putting in a pull request for Cache Cow's core client to be made portable...all its dependencies are.

**Comment by fubar-coder** [comment]
I just published Version 2.1.0-pre1 (prerelease). Please notify me when this version works as expected. Thank you.

**Comment by fubar-coder** [comment]
There's a new version 2.1.0-pre2, which should put the default HTTP header parameters into the HTTP client object.

**Comment by fubar-coder** [comment]
2.1.0-pre3 fixes the package to enable support for Xamarin.iOS

**Comment by ashic** [comment]
Seems to work. Thanks for the quick update :)

**Comment by simondebaecke** [comment]
Does this means that we also have to use the same RestClient object across the app (like a singleton) instead of each instance (for each request) using disposable statement ? :)

According posts and this commit, it's what I understand but I'm not sure to be right ...

**Comment by fubar-coder** [comment]
The HttpClient instance is tied to the RestClient instance. Otherwise, you wouldn't be able to release ask resources with a dispose. IOW: When you need the same HttpClient instance for multiple RestClient instances, then you have to provide your own factory that caches the first created HttpClient instance.

**Comment by simondebaecke** [comment]
Or instead, I re-use the same RestClient instance for each request to make. This is equivalent or even better, no ?

But at the end, what is the difference of performance between re-using a single RestClient instance (or like you said, the same HttpClient from RestClient) and using different instance for each request (with using statement) ?

**Comment by fubar-coder** [comment]
I guess that it's much better to use a single RestClient instance.

**Comment by simondebaecke** [comment]
Ok, sorry, I was really thinking my questions are related to this issue. ;)

I will contact you for shortly for a "ProtocolViolationException: The number of bytes to be written is greater than the specified ContentLength." exception when re-use of the same RestClient instance ... xD
