### ISSUE TITLE
RestClient Timeout

### ISSUE THREAD

**Issue by sohayb** [FubarDevelopment/restsharp.portable#13]
Hello,
Is there a way to set timeout to the rest client?
Thanks

**Comment by fubar-coder** [comment]
Just use a CancellationTokenSource with timeout.
```cs
var cts = new CancellationTokenSource(TimeSpan.FromSeconds(10));
var response = client.Execute(request, cts.Token);
```

**Comment by sohayb** [comment]
Thanks a lot :+1:

**Comment by fubar-coder** [comment]
BTW: When you need more control over the HttpClient, then you can still overload DefaultHttpClientFactory.CreateClient, call its base and modify its behavior.

**Comment by sohayb** [comment]
Cool!
Are you planning to add Actions (callbacks) with the async execution of requests in the future?

**Comment by fubar-coder** [comment]
I'm not really sure what you mean. Do you have more details about this feature?

**Comment by sohayb** [comment]
Like in this function from the original Restsharp library:
    RestRequestAsyncHandle ExecuteAsync<T>(IRestRequest request, Action<IRestResponse<T>, RestRequestAsyncHandle> callback);
by then I can execute requests like this, with erroCallBack is Action<String> and successCallback is Action
    client.ExecuteAsync(request, response =>
            {
                  if (forceError)
             {
                   errorCallBack("Failed");
             }
             else
             {
                   if (response.StatusCode == HttpStatusCode.OK)
                   {
                           successCallback();
                    }
                    else
                    {
                            errorCallBack("Failed");
                     }
                 }
     });

**Comment by fubar-coder** [comment]
Ah, now I understand. I thought about this too, but came to the conclusion that this isn't necessary for RestSharp.Portable, because it uses the TPC (async/await), which includes this feature anyway.
Instead of 
```cs
var response = await client.Execute(request);
```
you're also able to do the following:
```cs
client.Execute(request)
  .ContinueWith(t => {
    var result = t.Result;
    // do whatever you want with the result
  });
```

Another main difference between RestSharp and RestSharp.Portable is that failed requests already throw an exception (except when explicitly disabled), so there's no reason to manually check for the status code.

**Comment by sohayb** [comment]
The thing is that I want to isolate my communication layer as it's shared between different mono, windows and windows phone projects. so the callbacks should be passed from outside. So I can execute your provided code (with my callback) on success and in a catch block, I can execute my failure callback; like the following:
```
            try
            {
                _client.Execute<AppointmentResponse>(request).ContinueWith(t =>
                {
                    var result = t.Result;
                    successCallback((AppointmentResponse)result);
                });
            }
            catch(Exception ex)
            {
                failureCallback(ex.Message);
            }
```
What do you think?

**Comment by fubar-coder** [comment]
This is possible, but why don't you use RestSharp.Portable with async/await directly (or indirectly through a custom communication client), without the need to provide callbacks? The callback handler stuff seems to be overly complex.

BTW: The error handling should be done in the following way:
```cs
var execTask = client.Execute(request);
execTask
  .ContinueWith(t => {
    var result = t.Result;
    // do whatever you want with the result
  }, TaskContinuationOptions.OnlyOnRanToCompletion);
execTask
  .ContinueWith(t => {
    var exception = t.Exception;
    // do whatever you want with the exception
  }, TaskContinuationOptions.OnlyOnFaulted);
execTask
  .ContinueWith(t => {
    // do whatever you want with the cancellation
  }, TaskContinuationOptions.OnlyOnCanceled);
```

Be aware, that when you use ContinueWith or async/await, that the code inside the ContinueWIth or after the await might be executed in a different thread.

**Comment by sohayb** [comment]
Thank a lot, much appreciated :)

**Comment by simondebaecke** [comment]
Hi !

I allow myself to write here because it seems to be a continuation of the subject : strangely, your snippet doesn't seem to work like expected. Here is what I do to get things working.

```
CancellationTokenSource cts = new CancellationTokenSource ();
cts.CancelAfter (TimeSpan.FromSeconds (10));
response = await client.Execute<T> (request, cts.Token);
```

Am I missing something ? Thank you to enlighten me. =)

**Comment by fubar-coder** [comment]
Fear not! The new "Timeout" property comes to the rescue :grinning: . Just update to the version 2.4.0 and you don't have to fiddle with "CancelAfter" anymore. Be aware, that the timeout is only available as IRestClient property, because the HttpClient instance is kept alive as long as the RestClient instance is alive.

**Comment by simondebaecke** [comment]
Event better, thank a lot ! :)

**Comment by vdevappa** [comment]
What is the unit for the Timeout property? Seconds? Minutes?

**Comment by rubemalmeida** [comment]
"Timeout in milliseconds to use for requests made by this client instance"
ref: http://www.nudoq.org/#!/Packages/RestSharp/RestSharp/RestClient
