### ISSUE TITLE
OAuth 1.0 and OAuth1Authenticator custom Timestamp

### ISSUE THREAD

**Issue by Yurijj** [FubarDevelopment/restsharp.portable#15]
When we try to authenticate to some service with help of OAuth1Authenticator, the Autorization header will be generated automatically. It will looks like
"OAuth oauth_version=\"1.0\", oauth_signature_method=\"HMAC-SHA1\", oauth_nonce=\"8335006\", oauth_timestamp=\"1414663625\", oauth_consumer_key=\"9612eaca23c7bdd3eca60dc8c2a8159c\", oauth_signature=\"M6sLyyfHGYXOtQnLJexDx96kbFo=\", oauth_token=\"8d0e43fd0cc67726567d49ae5e818852\"";

And, for instance, I want to set custom time stamp, using server time for example, not client one. It is no way to set a custom "oauth_timestamp" during generation of Autorization header with help of OAuth1Authenticator. What if "OAuth1Authenticator" will have a property or method that allows developer  to set the time stamp?

some code:
var restClient = new RestClient(_serviceUrl);
var request = new RestRequest(RequestTokenRequest, Method.POST);
restClient.Authenticator = OAuth1Authenticator.ForRequestToken(_consumerKey, _consumerSecret);
((OAuth1Authenticator)restClient.Authenticator).SignatureMethod = OAuthSignatureMethod.PlainText;

// is it make sense?
((OAuth1Authenticator)restClient.Authenticator).TimeStamp = _customTimeStamp;

**Comment by fubar-coder** [comment]
Thanks for the suggestion. IMHO it's better to implement a delegate to provide a function that returns the correct "timestamp". I'll provide a test version soon (2.2.0-pre1).

**Comment by fubar-coder** [comment]
I just made version 2.2.0-pre1 available as NuGet package, where the timestamp can be set with:
```csharp
private string MyCustomTimestampProvider()
{
    string timestamp;
    // somehow calculate the timestamp and return it as string.
    return timestamp;
}
```

```csharp
// Set your custom timestamp provider.
((OAuth1Authenticator)restClient.Authenticator).TimeStamp = MyCustomTimestampProvider;
```

Please give me some feedback (by comment or by closing this issue). I'll release version 2.2.0 soon afterwards.

**Comment by Yurijj** [comment]
Ok, great. You are so fast) Will check later today/tomorrow and let you know.

**Comment by fubar-coder** [comment]
I forgot a small change (I'm completely in holiday mode :blush:). Please use 2.2.0-pre2 instead. Thank you.

**Comment by fubar-coder** [comment]
I guess that everything works as expected. I'll close this ticket now.

**Comment by Yurijj** [comment]
One quick question.. I can't access to RestSharp.Portable.Authenticators.OAuth1Authenticator in my current WP8.0 or WP8.1 apps.

But I can access to all classes that implements IAuthenticator interface:  
HttpDigestAuthenticator
HttpBasicAuthenticator
NtlmAuthenticator
SimpleAuthenticator
AsyncAuthenticator

What the problem might be? (I've installed RestSharp.Portable 2.2.0 with help of Nuget)

PS
Sorry If wrong place to ask my question

**Comment by fubar-coder** [comment]
I'll take a look at it tomorrow, because I don't have VS2012 installed now.

**Comment by fubar-coder** [comment]
Accessing the OAuth1Authenticator works for me. BTW: In 2.2.0 I disabled the construction with the "new" operator. You must use the static functions to create it. [Here](https://www.fubar-dev.de/downloads/TestWp80App1.zip) is a compilable, but otherwise empty application that references the OAuth1 authenticator.
