### ISSUE TITLE
Getting content when there's an exception

### ISSUE THREAD

**Issue by ashic** [FubarDevelopment/restsharp.portable#17]
For validation, etc. scenarios, it's useful to be able to access the response content in case of failure. I can see that the following is used:

```C#
 if (!this.IgnoreResponseStatusCode)
              response.EnsureSuccessStatusCode();
```

And that we can set Ignore... to false to get the IRestResponse with raw bytes, status code, etc. However, it's a bit tedious to then check whether it's successful or not. Specially since HttpClient provides am IsSuccessStatus helper. I think it would be useful to have this available in the response. I can think of three ways that may deal with this scenario (i.e. get content in case of failure):

1) Add a boolean to IRestResponse that basically takes the value of httpclient's IsSuccess flag.
2) Add an EnsureSuccessCode method on IRestResponse that throws an exception that has the RestResponse contents inside of it.
3) Instead of bubbling HttpClient's exception raised in Ensure..(), trap it and throw a different exception that has the payload, etc. in it. Guessing this would be a breaking change.

Having easy access to the content would allow clients to use validation messages, etc. without forcing them to do weird Message parsing (if errors aren't ignored), and without having to do validation around the IRestResponse status code (in case of ignoring errors).

Thoughts?

**Comment by fubar-coder** [comment]
This is a good idea. I think that the best solution is to add an "IsSuccess" flag to the RestResponse.

**Comment by ashic** [comment]
Yeah... that should meet the criteria and should be easy to do. Option 2 could be an extension method that clients can implement themselves if they're interested. Option 3 doesn't look attractive as it breaks clients.

**Comment by fubar-coder** [comment]
Version 2.3.0 is available now.
