### ISSUE TITLE
Ensure that requests aren't executed in parallel on the same RestClient

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/restsharp.portable#19]
Parallel execution on the same RestClient causes unexpected behaviors like:

* Could not create SSL/TLS secure channel
* System.Net.ProtocolViolationException: The number of bytes to be written is greater than the specified ContentLength

**Comment by simondebaecke** [comment]
I'm not sure to fully understand :  you prevent ProtocolViolationException but parallel requests with the same RestClient are blocked by semaphore (and so each request are executed one after the other, we lose the parallel benefit) or continue to kind of be executed in parallel ?

**Comment by fubar-coder** [comment]
Yes, that's correct, because the same HttpClient instance is shared between multiple requests now and HttpClient behaves badly (protocol violations, ssl/tls errors, etc...) when it's used in multiple parallel requests. Therefore you have to create your own RestClient instance when you want multiple requests in parallel. However, you can still share the authenticator instance if it's supported by the authenticator.
