### ISSUE TITLE
Response HTTP status

### ISSUE THREAD

**Issue by sohayb** [FubarDevelopment/restsharp.portable#20]
Hello,
there's a problem for me getting the HTTP Response in case of failure, I need to differentiate handling based on the returned status.
This is how I'm calling the service:
````csharp
            RestClient _client = new RestClient(new Uri(API_URL));
            _client.HttpClientFactory = new CustomHttpClientFactory();
            var request = new RestRequest(HttpMethod.Get);
            request.Resource = PATH_HEADER + "branches/{branchPublicId}/services/{servicePublicId}/dates";
            request.AddParameter("branchPublicId", branchPublicId, ParameterType.UrlSegment);
            request.AddParameter("servicePublicId", servicePublicId, ParameterType.UrlSegment);
            var execTask = _client.Execute<T>(request);
            execTask
              .ContinueWith(t =>
              {
                   var result = t.Result;
                   if (result.Data == null)
                       callback.Failure(new NullReferenceException(), "Result data is null");
                   else
                       callback.Success((T)result.Data);
              }, TaskContinuationOptions.OnlyOnRanToCompletion);
            execTask
              .ContinueWith(t =>
              {
                  var exception = t.Exception;
                  callback.Failure(exception, exception.Message);
              }, TaskContinuationOptions.OnlyOnFaulted);
`````
Is there something I'm missing, because I cannot parse "t" into RestResponse, just IRestResponse, in which I cannot get the HTTP response status.

Thank you

**Comment by fubar-coder** [comment]
Hi,

there's a StatusCode property defined for IRestResponse (as you can see [here](https://github.com/FubarDevelopment/restsharp.portable/blob/master/RestSharp.Portable/IRestResponse.cs#L46))

**Comment by sohayb** [comment]
Thanks a lot :)

**Comment by sohayb** [comment]
Hello,
I changed the code with management based on StatusCode from the IrestResponse interface, the thing is, this status code is not accurate. For example, when I execute a get request from the browser and I get ````Failed to load resource: the server responded with a status of 503 (Service Temporarily Unavailable)````, executing the same request using RestSharp Portable would end with a status 200. Am I missing something?
Thanks :)

**Comment by fubar-coder** [comment]
Uh, that's difficult to say.

* Are you sure, that both requests use exactly the same URL with the same GET/POST parameters?
* Did you test it from the browser using RESTClient on Firefox or Postman on Chrome?
* Did you take a look at the network communication?
  * You can use something like [Fiddler](http://www.telerik.com/fiddler) to watch the network communication. You can even decrypt HTTPS communication (if configured correctly).
* A 200 indicates success. Did you get the correct data?

If you still cannot find the problem, then you can send me an example project and I'll take a look. You can find my e-mail address here: [fubar-dev.de site notice](https://www.fubar-dev.de/site-notice).

**Comment by sohayb** [comment]
Thanks a lot, the server seems unstable now. Will send you a sample project as soon as it's stabilized and I get consistent responses.
Much appreciated.

**Comment by sohayb** [comment]
@fubar-coder email sent, much appreciated :)

**Comment by fubar-coder** [comment]
Hi,

I didn’t receive an email yet. Did you send it to m.junker@fubar-dev.de<mailto:m.junker@fubar-dev.de>?

Kind regards,
Mark

Von: Sohayb Hassoun [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. März 2015 12:02
An: FubarDevelopment/restsharp.portable
Cc: Mark Junker
Betreff: Re: [restsharp.portable] Response HTTP status (#20)


@fubar-coder<https://github.com/fubar-coder> email sent, much appreciated :)

**Comment by sohayb** [comment]
Sending the email from my gmail account failed, don't know why. Mail hopefully sent now from my outlook email.
Thank you

**Comment by fubar-coder** [comment]
Hi,

yes, I received the mail from the outlook account. I’ll take a look at the sample project tomorrow or during the weekend, because I have much work to do here…

Kind regards,
Mark


Von: Sohayb Hassoun [mailto:notifications@github.com]
Gesendet: Donnerstag, 5. März 2015 14:27
An: FubarDevelopment/restsharp.portable
Cc: Mark Junker
Betreff: Re: [restsharp.portable] Response HTTP status (#20)


Sending the email from my gmail account failed, don't know why. Mail hopefully sent now from my outlook email.
Thank you

**Comment by supreettare** [comment]
@sohayb could it be possible for you to share the code snippet on how you are handling the error responses based on status code, I need this & not able to work it out. 

Thanks in advance. 

ST
