### ISSUE TITLE
equivalent of FollowRedirects?

### ISSUE THREAD

**Issue by BrannonKing** [FubarDevelopment/restsharp.portable#21]
RestSharp's RestClient has a property called `FollowRedirects`. What is the equivalent of that in this library?

**Comment by fubar-coder** [comment]
Hi,

there's no such property (yet), but you can achieve the same result by using an overridden `DefaultHttpClientFactory`. I've published an example here: [FollowRedirectHttpClientFactory.cs](https://gist.github.com/d8eb45356a0bfd0cd405.git)

**Comment by BrannonKing** [comment]
It works perfectly. Thanks.
