### ISSUE TITLE
OAuth, OAuth2 multiple definitions in Android projects

### ISSUE THREAD

**Issue by gabornemeth** [FubarDevelopment/restsharp.portable#24]
If you add RestSharp.Portable.OAuth2 as NuGet package to your Xamarin Android app, you get
"The type 'RestSharp.Portable.Authenticators.Resource' exists in both..." error messages because ApplicationName and Hello string resources defined in both RestSharp.Portable.OAuth and RestSharp.Portable.OAuth2 assembly.

**Comment by fubar-coder** [comment]
Please try again with 2.4.1. The problem should be fixed now.

**Comment by gabornemeth** [comment]
It's working fine now.
