### ISSUE TITLE
Does FubarCoder.RestSharp.Portable.OAuth package can be installed in Windows 10 UAP Class Library?

### ISSUE THREAD

**Issue by Yurijj** [FubarDevelopment/restsharp.portable#27]
I'm trying to install FubarCoder.RestSharp.Portable.OAuth to use OAuth1Authenticator class in my application Class Library (Windows Universal). But package manager console indicate an error such as:

PM> Install-Package FubarCoder.RestSharp.Portable.OAuth
Attempting to gather dependencies information for package 'FubarCoder.RestSharp.Portable.OAuth.2.4.3' with respect to project targeting 'Windows, Version=v8.1'
Attempting to resolve dependencies for package 'FubarCoder.RestSharp.Portable.OAuth.2.4.3' with DependencyBehavior 'Lowest'
Install-Package : Unable to satisfy package dependency constraints.
At line:1 char:1
+ Install-Package FubarCoder.RestSharp.Portable.OAuth
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Install-Package], Exception
    + FullyQualifiedErrorId : NuGetCmdletUnhandledException,NuGet.PackageManagement.PowerShellCmdlets.InstallPackageCommand
 

Is the a chance to FubarCoder.RestSharp.Portable.OAuth package will support and can be installed under Class Library (Windows Universal) project type?

P.S.
I've successfully installed FubarCoder.RestSharp.Portable -Version 2.4.3 into my Windows10 project - BlankApp (Windows Universal).

**Comment by fubar-coder** [comment]
Windows 10 universial apps will definitely be supported. I'll take a look at it soon.

**Comment by Yurijj** [comment]
Ok, great news! Will be waiting for it!

**Comment by Yurijj** [comment]
Portable Class Libraries Contrib: http://pclcontrib.codeplex.com/
It includes a port of HMACSHA1, maybe can be useful for FubarCoder.RestSharp.Portable.OAuth portable one.

**Comment by fubar-coder** [comment]
I'm currently not able to fix this problem, because VS 2015 RC doesn't work with the Xamarin (causes the C# compiler to exit with status 1). I'll add UWP support as soon as those problems are fixed by Microsoft and/or Xamarin.

**Comment by mylemans** [comment]
What is the current state on this now that it is out?

**Comment by fubar-coder** [comment]
My latest test shows that RestSharp.Portable 2.4.4 (including OAuth/OAuth2) can be installed in a UWP project without problems. Don't hesitate to leave another comment when you encounter problems and I'll reopen this issue.
