### ISSUE TITLE
Timeout not working on Android (Xamarin)

### ISSUE THREAD

**Issue by wdcossey** [FubarDevelopment/restsharp.portable#28]
Hey fubar-coder,

Seems that the Timeout property on IRestClient doesn't work on Android. :/

      var source = new CancellationTokenSource();
      source.CancelAfter(TimeSpan.FromSeconds(10));
      
      using (IRestClient client = new RestClient("http://www.somerandomserverurl.com"))
      {
        client.Timeout = TimeSpan.FromSeconds(10);

        var request = new RestRequest("Request", HttpMethod.Get);
        try
        {
          return await client.Execute(request, source.Token);
        }
        catch (Exception ex)
        {
          throw;
        }
      }

It would also appear that the CancellationToken doesn't work, I find myself waiting the 100+ seconds for the HttpClient to timeout which is rather painful (not the expected System.AggregateException/TaskCanceledException).

Perhaps I'm doing something incorrectly, your help would be greatly appreciated.

**Comment by fubar-coder** [comment]
This it's strange. I'll do some tests during the next week. It might be a limitation of the HttpClient implementation for Android. I'm currently working on 3.0 which allows different HTTP implementations to be used. Maybe using WebRequest as a replacement helps.

**Comment by wdcossey** [comment]
Hey fubar-coder,

It seems that it's an issue with the HttpClient used by Xamarin (if that's used by default in RestSharp.Portable?) , the issue goes way back.

https://bugzilla.xamarin.com/show_bug.cgi?id=13200

I just ran a simple test using Microsoft's HTTP Client Libraries (https://www.nuget.org/packages/Microsoft.Net.Http)

      using (var handler = new HttpClientHandler())
      using (var client = new HttpClient(handler))
      {
        client.BaseAddress = new System.Uri("http://192.168.1.20/myRandomService.svc");
        //This url is purposely NOT reachable to test the timeout.

        var message = new HttpRequestMessage(HttpMethod.Get, new System.Uri("Testing", UriKind.RelativeOrAbsolute));

        client.Timeout = TimeSpan.FromSeconds(10);
        try
        {
          await client.SendAsync(message);
        }
        catch (Exception ex)
        {
          throw;
        }
      }

I get the expected System.Threading.Tasks.TaskCanceledException.

Is there any chance that I could use the Microsoft HttpClient with RestSharp.Portable, without having to integrate Json.NET deserialization "manually"?

**Comment by fubar-coder** [comment]
The Microsoft HttpClient package uses Xamarins HttpClient implementation. I hope to release 3.0 within the next two weeks, which should fix this problem by using WebRequest as IHttpClient implementation. 3.0 will bring some breaking changes, but it'll also bring more flexibility like using a native TcpClient as IHttpClient implementation with Socks4/4a/5 support (some time after the 3.0 release).

**Comment by fubar-coder** [comment]
The 3.0.0 alpha 10 release has a package that uses [WebRequest](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.WebRequest/3.0.0-alpha10) instead of [HttpClient](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.HttpClient/3.0.0-alpha10). This should allow you avoiding Xamarins flawed ```HttpClient``` implementation.
