### ISSUE TITLE
Add a HAL deserializer

### ISSUE THREAD

**Issue by codeaid** [FubarDevelopment/restsharp.portable#30]
Hi! 

Firstly thanks for your work on the library! It's been a great help so far, however one thing I'd love to have in it is missing - a HAL deserializer. One that would support the `_links` and `_embedded` properties. I am currently working on a project consuming an API that spits out HAL and I'm having difficulties building models with nested entries.

I thrawled the net trying to either find a library that would do it for me or a standalone deserializer but with no luck and thought it would be awesome if there was one shipped with Restsharp Portable.

Obviously feel free to close this "issue" but I would appreciate any kind of answer from you, even if it's a no.

Thanks!

**Comment by fubar-coder** [comment]
Hi, do you mean the [JSON-HAL](http://stateless.co/hal_specification.html) specification? Do you have a proposal what (and how it) needs to be done to support this in a useful way? To me, this looks like a mixture of (de-)serializing and proxying (for the most comfortable usage). Wouldn't something like the following fit your needs?

* [halclient](https://github.com/ecomfi/halclient)
* [HalClient.Net](https://github.com/wis3guy/HalClient.Net)
* [HalKit](https://github.com/viagogo/HalKit)

[This site](https://github.com/mikekelly/hal_specification/wiki/Libraries) has a list of libraries for C# (and for other languages as well).
