### ISSUE TITLE
HttpRequestException 500 (Internal Server Error) - Hangs in iOS POST Request

### ISSUE THREAD

**Issue by adamfisher** [FubarDevelopment/restsharp.portable#31]
I am trying to POST data using a Xamarin iOS unit test project and I can successfully make GET requests but when I try to do a POST it always fails. My web service also has Swagger documentation and I was able to POST data using that but never with this library. Is this a good example of how to call it for a POST request?

When the client.Execute() method is invoked, it returns the error below. I also verified no network traffic occurs from the mobile client when proxy through Fiddler.

```csharp
var payload = new User()
{
	FirstName ="Suzy",
	LastName = "Q",
	Age = 43
};

using (var client = new RestClient("http://mywebservice.com:8308"))
{
	var request = new RestRequest("api/Accounts/Register", HttpMethod.Post);
	request.AddJsonBody (payload);
	var result = await client.Execute<UserRegistrationResponse>(request);
	var userId = result.Data.UserId;
}
```

![ios simulator screen shot jun 1 2015 10 46 06 am](https://cloud.githubusercontent.com/assets/1834711/7915486/d63b7afc-084b-11e5-9cd0-1fb6f66ae77e.png)

**Comment by fubar-coder** [comment]
Can you please try to add the "User-Agent" header? It often happens that a missing "User-Agent" header results in strange behavior (HTTP errors).

**Comment by adamfisher** [comment]
No dice. Adding the header didn't work. I am proxying all network traffic from my Mac through Fiddler and I see the traffic for GET (so I know I can reach the server) but POSTs don't even show a request. It's like it fails inside the library before it ever gets a chance to fire off the request.

**Comment by adamfisher** [comment]
Have you been able to do POSTs inside an iOS simulator?

**Comment by fubar-coder** [comment]
I only test this sporadically, but I'll test this tomorrow on a Mac.

**Comment by fubar-coder** [comment]
I tried to test this project using Xamarin Studio, but I forgot how bad it is... I'll try again tomorrow.

**Comment by simondebaecke** [comment]
If it can help, I use RestSharp.Portable on my daily basis for Xamarin development (Android and iOS) and any type of request is working fine. ;)

**Comment by adamfisher** [comment]
It turns out there was a 500 error that was getting shielded by the awaiting activation task status. Just need to fix my service layer. Sorry for the trouble.

**Comment by fubar-coder** [comment]
Thank you for letting me know.
