### ISSUE TITLE
RestClient CookieContainer always empty  after response that sets cookies

### ISSUE THREAD

**Issue by web-roman** [FubarDevelopment/restsharp.portable#32]
Hi, I have a question about CookieContainer.
Maybe i'm doing something wrong but in latest version of restsharp.portable CookieContainer after response that sets cookies always empty. In previous version all worked fine. 
Thanks)

**Comment by fubar-coder** [comment]
Which version exactly? 2.4.3 or the 3.0 alpha?

**Comment by web-roman** [comment]
2.4.3

**Comment by fubar-coder** [comment]
I added a unit test for this issue in the commit 1cc962ac75fdde58bc1f38dd01514834c866f6dd and I was unable to reproduce the problem.

**Comment by fubar-coder** [comment]
Maybe you can provide a test case where I can see the problem?

**Comment by web-roman** [comment]
i'v tried to get cookies from restclient.CookieContainer, not from response.Data.Cookies. Thanks)

**Comment by fubar-coder** [comment]
So did I as you can see [here](https://github.com/FubarDevelopment/restsharp.portable/commit/1cc962ac75fdde58bc1f38dd01514834c866f6dd#diff-8023268b20fa1094100e19a296ea0c36R181)

**Comment by web-roman** [comment]
Thanks now i see where i'v made mistake now i fixed it and all works fine.Sorry for disturb.

**Comment by fubar-coder** [comment]
No problem :smile: . Glad that I could help you.
