### ISSUE TITLE
Use ModernHttpClient Instead of DefaultHttpClientFactory

### ISSUE THREAD

**Issue by adamfisher** [FubarDevelopment/restsharp.portable#34]
Is there an easy way to replace the HttpClientFactory on the client so it uses [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient)'s NativeMessageHandler? 

This is my initial stab at integrating it but I didn't see a way to set the _proxyProperty from the DefaultHttpClientFactory the same way it did.

```csharp
/// <summary>
    /// An HTTP Client Factory that uses the high-performance ModernHttpClient's NativeMessageHandler to process requests.
    /// </summary>
    public class ModernHttpClientFactory : DefaultHttpClientFactory
    {
        #region Methods

        /// <summary>
        /// Create the message handler.
        /// </summary>
        /// <param name="client">The REST client that wants to create the HTTP client</param>
        /// <param name="request">The REST request for which the HTTP client is created</param>
        /// <returns>
        /// A new HttpMessageHandler object
        /// </returns>
        protected override HttpMessageHandler CreateMessageHandler(IRestClient client, IRestRequest request)
        {
            var proxy = GetProxy(client);
            var cookies = GetCookies(client, request);
            var credentials = client.Credentials;
            var httpClientHandler = new NativeMessageHandler();

            if (httpClientHandler.SupportsProxy && proxy != null)
            {
                httpClientHandler.UseProxy = true;
                httpClientHandler.Proxy = new RequestProxyWrapper(proxy); ;
            }

            if (cookies != null)
            {
                httpClientHandler.UseCookies = true;
                httpClientHandler.CookieContainer = cookies;
            }

            if (credentials != null)
            {
                httpClientHandler.Credentials = credentials;
            }

            return httpClientHandler;
        }

        #endregion
    }
```

**Comment by fubar-coder** [comment]
Yes, that's essentially it. Please don't forget to set the cookies, proxy, and credentials for the message handler.

**Comment by fubar-coder** [comment]
You can get the proxy using:

```csharp
var proxy = GetProxy(client);
```

Cookies:
```csharp
var cookieContainer = GetCookies(client, request);
```

Credentials:
```csharp
var credentials = GetCredentials(request);
```

**Comment by adamfisher** [comment]
Sorry I revised my original answer with the new implementation. The only thing I couldn't figure out when comparing it to the overriden code in DefaultHttpClientFactory was whether I handled the proxy correctly. Does it look correct to you?

**Comment by fubar-coder** [comment]
Looks good to me.

**Comment by adamfisher** [comment]
Thank you so much! Now I just invoke it in my client using:

```csharp
client.HttpClientFactory = new ModernHttpClientFactory();
```

**Comment by adamfisher** [comment]
I'm finally getting back to this and I have come across a couple of issues:

- Cannot implicitly convert type 'RestSharp.Portable.IRequestProxy' to 'System.Net.IWebProxy'.
- Cannot implicitly convert type 'RestSharp.Portable.IRestRequest' to 'System.Net.ICredentials'.

Could you please provide some insight into converting the proxy and credentials into the format expected by the httpClientHandler?

![](https://cloud.githubusercontent.com/assets/1834711/15714840/2d27e094-27ea-11e6-84b0-77cffdd3e293.PNG)
