### ISSUE TITLE
Must append BaseUrl

### ISSUE THREAD

**Issue by lakario** [FubarDevelopment/restsharp.portable#35]
Not sure what I am missing here, but the client is forcing me to append the BaseUri to my resource URLs, or else I always get a 404. This is contrary to the example code, and the exact same implementation works when I substitute RestSharp.Portable for RestSharp.

    public class MyService
    {
        private readonly RestClient _client;

        public MyService()
        {
            _client = new RestClient("https://api.mywebsite.com/1");
        }

        public async Task<IList<Event>> GetEventsAsync()
        {
            // why do i need to append the base url?
            var request = new RestRequest(_client.BaseUrl + "/events?api_key={api_key}&query={query}", HttpMethod.Get);

            request.AddUrlSegment("api_key", "api_key_here");
            request.AddUrlSegment("query", "dodgers");

            var response = await _client.Execute<ApiResponse<Event>>(request);

            if (response.Data == null)
            {
                throw new Exception(":(");
            }

            return response.Data.Results;
        }
    }

**Comment by lakario** [comment]
Okay, the issue is related to slashes. If I drop the "/" from in front of the resource name, everything works as it should.

**Comment by fubar-coder** [comment]
Your observation is correct, and it is indeed something that's done differently by this library, because it allows real URI combinations which makes the usage of [JSON-HAL](http://stateless.co/hal_specification.html) easier which may make usage of host-relative URLs.
