### ISSUE TITLE
Creating a response object in case of exception 

### ISSUE THREAD

**Issue by supreettare** [FubarDevelopment/restsharp.portable#36]
Apologies for duplicate post, I posted the same question on your reddit before 
https://www.reddit.com/r/FubarDev/comments/3cagk7/creating_a_response_object_to_handle_exceptions/

When using the full restSarp library we use the following code snippet to create a response object in case of an exception occurs.

```csharp
try
            {
 response = await client.ExecuteTaskAsync<T>(request, new CancellationTokenSource(30000).Token);
            }
catch (Exception exception)
         {
            response = new RestResponse<T>
                { 
                    ResponseStatus = exception is TaskCanceledException ? ResponseStatus.TimedOut     :ResponseStatus.Error,
                ErrorException = exception
            };
        } 
```

Since ResponseStatus & ErrorException are not available in this version of port, what are my options to create a response object in case of an exception? 
Thanks

**Comment by fubar-coder** [comment]
You may use the following functionality when you don't want exceptions and want to handle the status code yourself:

```csharp
try {
  client.IgnoreResponseStatusCode = true;
  var response = await client.Execute<T>(request, new CancellationTokenSource(30000).Token);
  if (!response.IsSuccess) {
    // You may query the status code using response.StatusCode
  }
} catch (TaskCancelledException) {
  // Cancellation token
}
```

Be aware, that the ```IRestClient``` itself has a ```Timeout``` property that you may set to 30 seconds without using the cancellation token.

Please write a comment when you have further questions.

**Comment by supreettare** [comment]
Fantastic :) Thank you 
P.S. I love this library :)
