### ISSUE TITLE
Nested object are always null

### ISSUE THREAD

**Issue by florian-santi** [FubarDevelopment/restsharp.portable#37]
Hello,
First thanks a lot for your great work... :-) 
I've a big issue with nested object on PUT/POST calls.
My object definition:

```csharp
public class ObjectA 
{
    public string Name {get; set;}
    public ObjectB MyObjectB {get; set;}
}

public class ObjectB 
{
    public string Description {get; set;}
}
```
Now I'm trying to POST a new object to my REST API with the code bellow:

```csharp
var myObjectA = new ObjectA
{
    Name = "My Object A",
    MyObjectB = new ObjectB 
    {
        Description = "My nested ObjectB"
    }
};

var resClient = new RestClient
{
    BaseUrl = new System.Uri("http://mybaseurl/"),
    TimeOut = 30
};
var restRequest = new RestRequest("ObjectsA", HttpMethod.Post);
resRequest.AddObject(myObjectA);
var restResponse = await restClient.Execute<ObjectA>(restRequest);
```

Now my REST API looks like this:

```csharp
 [System.Web.Http.HttpPost]
 [System.Web.Http.AcceptVerbs("POST")]
 [ResponseType(typeof(ObjectA))]
public async Task<IHttpActionResult> PostObjectAAsync(
            [FromBody]ObjectA myNewObjectA)
{
    try
        {
              // check if the parameter are deserialized
              if (!ModelState.IsValid)
          {
                    return BadRequest(ModelState);
           }
....
}
```

My problem is my myNewObjectA.MyObjectB property is always null and it's the same for all the object properties...other scalar type properties are correct.

Thanks for your support !!!
Kind regards,
Florian

**Comment by fubar-coder** [comment]
I'll take a look at this soon.

**Comment by fubar-coder** [comment]
The problem is the ```AddObject```. You have to use ```AddJsonBody``` instead, because AddObject adds all public object members as parameter to the request instead of creating a JSON document in the body.

**Comment by florian-santi** [comment]
Thanks for your time :-)
I implemented the change but now I've an expection ({"Response status code does not indicate success: 415 (Unsupported Media Type)."}) on the line 

var restResponse = await restClient.Execute<ObjectA>(restRequest);

and my WebAPI is not called anymore !!!

**Comment by fubar-coder** [comment]
That's difficult to tell. In your example code, I saw that you use ```ObjectsA``` instead of ```ObjectA``` as URL which would indicate the wrong action name. Maybe you somehow removed the JSON support in your Web API? What happens when you add ```[ActionName("ObjectA")]``` to your async Web API function?

**Comment by fubar-coder** [comment]
When you need further assistance, then I'd be willing to help, but I need a test application/server. Just send an e-mail to me and we can start finding the root cause.

**Comment by florian-santi** [comment]
Hello Mark,

I found the problem but I know how to figure out with…
In fact as soon as my object has a DateTime property, my WebApi is not able to deserialize the Json data, any advice on the RestRequest to specifiy a date format ?

Regards,
Florian

**Comment by fubar-coder** [comment]
You have to use your own JsonSerializer and JsonDeserializer.

For JsonSerializer:

* Override ```JsonSerializer.ConfigureSerializer``` and configure the serializer to use a MS-JSON compatible timestamp format
* Set the ```IRestRequest.Serializer``` property of the request to your custom JSON serializer
* Add the object to be serialized using the ```AddBody``` extension function

For JsonDeserializer:

* Override ```JsonDeserializer.ConfigureSerializer``` and configure the serializer to use a MS-JSON compatible timestamp format
* Use the ```IRestClient.ReplaceHandler(Type, IDeserializer)``` to replace the JSON deserializer with your own using ```client.ReplaceHandler(typeof(JsonDeserializer), new CustomJsonDeserializer())```

This should make the JSON serialization/deserialization compatible with the MS-JSON.
