### ISSUE TITLE
Is there a way to set the user agent?

### ISSUE THREAD

**Issue by davevr** [FubarDevelopment/restsharp.portable#40]
In RestSharp there is a UserAgent property on the RestClient object. Any equivalent here?

**Comment by fubar-coder** [comment]
Yes, you can use

```csharp
restClient.AddDefaultParameter("User-Agent", "your-user-agent", ParameterType.HttpHeader);
```

I decided against a specific property for the user agent, because it might clash with the default parameter that you can set too.
