### ISSUE TITLE
[Android] Not Honouring Proxy Settings

### ISSUE THREAD

**Issue by dazinator** [FubarDevelopment/restsharp.portable#45]
We have an issue where it doesn't appear the Android Proxy settings are used when making a request using RestSharp Portable.

**Comment by dazinator** [comment]
Nevermind - have established that I need to be setting the proxy manually by implementing `IWebProxy`

**Comment by dazinator** [comment]
So I still cannot get this to work. Here is the issue:

1. I created an IWebProxy Implementation for Android:

```csharp
 public class DroidProxy : IWebProxy
    {
        private static bool _IsIcsOrLater = Build.VERSION.SdkInt >= BuildVersionCodes.IceCreamSandwich;

        private System.Net.ICredentials _Credentials = null;

        private string _ProxyAddress;
        private int _ProxyPort;

        public DroidProxy(Context context)
        {
            if (_IsIcsOrLater)
            {
                _ProxyAddress = global::Android.Net.Proxy.DefaultHost;
                var port = global::Android.Net.Proxy.DefaultPort;
                if (port != null)
                {
                    if (!int.TryParse(port.ToString(), out _ProxyPort))
                    {
                        _ProxyPort = 80;
                    }
                }     

            }
            else
            {
                _ProxyAddress = Proxy.GetHost(context);
                _ProxyPort = Proxy.GetPort(context);
            }
        }

        public ICredentials Credentials
        {
            get
            {
                return _Credentials;
            }
            set
            {
                _Credentials = value;
            }
        }

        public Uri GetProxy(Uri destination)
        {
            return new Uri(string.Format("http://{0}:{1}", _ProxyAddress, _ProxyPort));
        }

        public bool IsBypassed(Uri host)
        {
            return true;
        }
    }
```

I am constructing the RestSharp.Portable Client like so:

```csharp
 private RestClient GetClient(string url)
        {    

           var client = new RestClient(url);
            client.Authenticator = _Authenticator; // I have a custom authenticator.
            client.Proxy = _Proxy; // An instance of my Android proxy class.
         
            client.Timeout = new TimeSpan(0, 1, 0);
            client.IgnoreResponseStatusCode = true; // this means it won't throw an exceptiohen there is one, and we can handle response status code ourselves.           
            return client;
        }
```

However when I then Execute a Request:

```
 var response = client.Execute(request).Result;
```

The IWebProxy implementation is not called at all..

Putting a breakpoint inside IWebProxy.GetProxy() and IWebProxy.IsBypassed - and they are not hit.

Am I doing something wrong?

**Comment by dazinator** [comment]
Could this be the reason: https://github.com/FubarDevelopment/restsharp.portable/blob/9390b959555ce91443ee589ac5031cc3b50af15e/RestSharp.Portable.WebRequest/Impl/Http/DefaultHttpClient.cs#L102

Perhaps I am reading that line incorrectly as I am not very familiar with this library - but shouldn't the Proxy be assigned to the `WebRequest` irrespective of 'PCL' compilation?

**Comment by fubar-coder** [comment]
Looks good to me. Maybe it's a problem with Xamarin HttpClient? You may also try to use [ModernHttpClient](https://components.xamarin.com/view/modernhttpclient), also available on [GitHub](https://github.com/paulcbetts/ModernHttpClient). When you have problems with ```ModernHttpClient```, please take a look at paulcbetts/ModernHttpClient#44. You can also find additional information in Issue #1. As last resort, you can also try the WebRequest variant of [RestSharp.Portable](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.WebRequest).

The source code is correct, because (sadly) the ```HttpWebRequest.Proxy``` property isn't supported in a PCL. However, it's active when you use the Android library, which is installed when you add the NuGet package to your Android project. That's the way the [Bait-And-Switch PCL trick](http://log.paulbetts.org/the-bait-and-switch-pcl-trick/) works.

Please feel free to leave a comment when you solved the problem or need further assistance.

**Comment by dazinator** [comment]
Switching to using the ModernHttpProxy has solved the problem for me. Just a simple case of creating a HttpClientFactory:-

```
 public class DroidHttpClientFactory : DefaultHttpClientFactory
    {
        protected override HttpMessageHandler CreateMessageHandler(IRestClient client, IRestRequest request)
        {
            return new NativeMessageHandler();
        }
         
    }
```

Funnily enough - I have linked an issue with another library that I am seeing the same issue with - so it must be something in the default HttpClient implementation not respecting android system proxy settings.

**Comment by dazinator** [comment]
And thank you for pointing me towards ModernHttpClient :-)

**Comment by fubar-coder** [comment]
No problem, I'm here to help 😊
