### ISSUE TITLE
Execute<T>(Request)

### ISSUE THREAD

**Issue by fravezzimattia** [FubarDevelopment/restsharp.portable#47]
I'm trying Restsharp.portable library in xamarin,
When I try to execute my Request it's seems dead, When the application call client.Execute method it freezing without launch any exception!! 

var client = new RestClient();
client.BaseUrl = new Uri(this.BaseUrl);
client.ClearHandlers();
Request.AddHeader("Authorization", "Basic " + credentials);
var response = await client.Execute<T>(Request);

If I try to send request from unitTest it works, but when I try to send form xamarin application no!
Why?

Thanks
Mattia

**Comment by fubar-coder** [comment]
I'll try to test it with a small Android app, or do you use iOS?

**Comment by fubar-coder** [comment]
Just an idea: The freeze might happen due to some strange behavior of ```HttpClient```. It's required to be run in the background/asynchronously. In other words: Don't do a ```.Wait()``` or ```.Result``` on the task in a non-```async``` event handler. The applications events must be processed to avoid a freeze.

**Comment by evnik** [comment]
Freezing on **async** methods usually means deadlock on restoring of context. Try this
```C#
var response = await client.Execute(Request).ConfigureAwait(false);
```

**Comment by fubar-coder** [comment]
Closed due to inactivity

**Comment by Nightw0rk** [comment]
@fubar-coder, Same problem. `Execute `never finished. Try in WPF Application, Net. Framework 4
```cshap
private RestRequest GetRequestClientLicense(string path, Method method, string fields, out RestClient client)
        {
            client = new RestClient(_authService.CHost);
            var request = new RestRequest(path, method);
            request.AddQueryParameter("key", _authService.License);
            if (fields != string.Empty)
            {
                request.AddQueryParameter("fields", fields);
            }            
            return request;
        }

public async Task<List<IModel>> GetsByLicense(string address)
        {
            RestClient client;
            var request = GetRequestClientLicense(address, Method.GET, string.Empty, out client);
            var cts = new CancellationTokenSource();
            cts.CancelAfter(TimeSpan.FromSeconds(2));
            var task = await client.Execute(request,cts.Token);
            return new List<IModel>();
        }
```

And Run

```cshap
var s = service.GetsByLicense("/desktop/user");
Console.WriteLine(s.Result);
```

**Comment by fubar-coder** [comment]
The `s.Result` is the problem. It's a limitation of the underlying HttpClient that it requires a running GUI thread event queue. You have to make your event handler `async` and `await` the result.

**Comment by Nightw0rk** [comment]
Thanks!
