### ISSUE TITLE
NullReferenceException on Dispose of DefaultHttpResponseMessage

### ISSUE THREAD

**Issue by thefex** [FubarDevelopment/restsharp.portable#53]
https://github.com/FubarDevelopment/restsharp.portable/blob/c2bc6b0ce43414a287e7c5ccbdf0dfae046e6875/RestSharp.Portable.HttpClient.Shared/Impl/Http/DefaultHttpResponseMessage.cs

NullReferenceException is thrown on dispose.
To reproduce error use RestClient.Execute while internet is disabled.

Problem lies in fact that ResponseMessage is null when there is no internet connection.

**Comment by fubar-coder** [comment]
Closed, because I haven't encountered the problem after the 3.1 release.
