### ISSUE TITLE
HttpBasicAuthenticator does not support pre-authenticate

### ISSUE THREAD

**Issue by dermeister0** [FubarDevelopment/restsharp.portable#55]
HttpBasicAuthenticator fills token after challenge handling only. However, my server does not return appropriate WWW-Authenticate header.

I added following constructor for myself:
```
        public HttpBasicAuthenticator(string username, string password)
        {
            _authToken = Convert.ToBase64String(Encoding.UTF8.GetBytes($"{username}:{password}"));
        }
```

Similar constructor presents in RestSharp: https://github.com/restsharp/RestSharp/blob/master/RestSharp/Authenticators/HttpBasicAuthenticator.cs

**Comment by fubar-coder** [comment]
Fixed in 3.1.2
