### ISSUE TITLE
Gzip config supported?

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#59]
Hi

Restsharp hard codes gzip headers. Does this lib allow configuration of this?

Thanks

**Comment by fubar-coder** [comment]
You can do the following:

- Add Gzip encoding (from [FubarCoder.RestSharp.Portable.Encodings](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.Encodings/) package) using the AddEncoding function
- Remove the default parameter `Accept` (`client.RemoveDefaultParameter("Accept");`)
- Add your own `Accept` default parameter

The `Accept` HTTP header gets only updated when you change the encodings. When you've configured your client, you can change the `Accept` header value to whatever you like.

**Comment by jchannon** [comment]
Just to clarify do you mean Accept-Encoding?

**Comment by fubar-coder** [comment]
Yes, you're right. My fault. I meant `Accept-Encoding`.
