### ISSUE TITLE
Execute synchronous version?

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#62]
Hi,

Am I right in thinking on RestClient is async? Is there a synchronous version anywhere or do I just have to call `.Result`?

Thanks

**Comment by fubar-coder** [comment]
Yes, the library is 100% async. Calling `.Result` is what you have to do in case you're not using async/await.

**Comment by jchannon** [comment]
Thanks

**Comment by daniloneto** [comment]
Hello, this not worked for me. For some reason remained stopped. No exception. You could send a synchronous example working?

**Comment by fubar-coder** [comment]
It depends on the platform. When you use it on Android or iOS, then it might be a good idea to use the [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient).
