### ISSUE TITLE
Switch to project.json and explicitly support netstandard

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/restsharp.portable#64]
This (maybe) requires splitting the project into more (smaller) packages, that target different `netstandard` versions (XML de/serialization). It would also reduce the huge amount of project folders, as we can see here:
- [before](https://github.com/dataline-gmbh/ExtraStandard/tree/3134746b8e5fa19052f91ec59dce238b6a578041)
- [after](https://github.com/dataline-gmbh/ExtraStandard/tree/master/src)

We should really wait for the .NET Core RC2, because there are still many changes done to .NET CLI, CoreFX, CoreCLR, and NuGet

**Comment by jchannon** [comment]
RC2 is out, go go go 😄

**Comment by fubar-coder** [comment]
I'm already trying, but dotnet test (with xUnit) is currently broken. I'm currently trying to write a new issue about this problem :disappointed:

**Comment by fubar-coder** [comment]
In the [release/4.0](https://github.com/FubarDevelopment/restsharp.portable/tree/release/4.0) branch is the first prototype. Some things are still missing, and I don't know if they are relevant or even possible.

Platforms:

- [X] Support for netstandard 1.1 (.NET 4.5, profile 111)
- [X] Support for netstandard 1.3 (native cryptography)
- [X] Support for .NET 4.0
- [ ] Support for C++/CLI
- [ ] Support for netstandard 1.0 (Windows Phone Silverlight)
- [ ] Support for SL5 (maybe through profile 328)

Other:

- [X] Unit tests for OAuth 1.0
- [ ] Unit tests for OAuth 2.0 (NUnit support is currently [missing](https://github.com/nunit/nunit/issues/1371))

I'll try to release a 4.0.0-alpha1-* release soon.

**Comment by jchannon** [comment]
nice work!

**Comment by fubar-coder** [comment]
I created a myget feed where the 4.0.0 alpha version is available. On the [RestSharp.Portable MyGet Gallery](https://www.myget.org/gallery/restsharp-portable) page, you can find the NuGet feed URL where you can download the test packages from.

**Comment by jchannon** [comment]
Don't suppose you have a rough ETA of v4 going to nuget?

**Comment by fubar-coder** [comment]
Not yet. I guess that it'll go live on nuget.org when the tooling reaches preview 2.

**Comment by fubar-coder** [comment]
There are still 2 points open for the 4.0 .NET Core compatible release as you can see above. The bug in dotnet-cli is fixed, bot not officially released yet. The other problem is, that it seems that I have to convert all NUnit tests to XUnit, because dotnet-cli doesn't support different unit test runners for different projects.

**Comment by kamranayub** [comment]
Preview2 tooling is out now, is this about ready then?

**Comment by fubar-coder** [comment]
I have to do minor (compatibility related) changes to have a release, that is "good enough" (tm), but I'm currently under high workload for other projects. I try to release the 4.0 version during this week.

**Comment by kamranayub** [comment]
No worries, I'm just in the process of assessing updating my project to
Core so just gauging readiness.
