### ISSUE TITLE
Unable to add restsharp.portable package in monodevelop in ubuntu

### ISSUE THREAD

**Issue by jeevanrd** [FubarDevelopment/restsharp.portable#68]
I am a newbie to c#.  when I add restsharp.portable from nuget Gallery , I Keep geting
"Adding FubarCoder.RestSharp.Portable...
Attempting to resolve dependency 'FubarCoder.RestSharp.Portable.HttpClient (≥ 3.2.0)'.
Downloading FubarCoder.RestSharp.Portable.HttpClient 3.2.0...
Object reference not set to an instance of an object"

Pls advise?

Thanks in advance
jeevan

**Comment by fubar-coder** [comment]
I guess, that it's a problem with MonoDevelop. I tested it with Xamarin Studio, which is a descendant of MonoDevelop and the package could be added without problem. You can try adding it manually:

1. Add FubarCoder.RestSharp.Portable.Core and FubarCoder.RestSharp.Portable.HttpClient to the `packages.config`
2. Restore the packages with `mono ./nuget.exe restore path-to/packages.config` (or something similar)

Now, you can use the packages from your project. You can download the latest `nuget.exe` from [here](https://dist.nuget.org/index.html).

PS: Maybe you can use VS Code together with .NET Core?

**Comment by jeevanrd** [comment]
Thanks @fubar-coder. Will try your suggestions.
