### ISSUE TITLE
PUT/POST form content is not quite right

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#69]
Hi,

We've spotted something odd when using the below code:

```
 var client = new RestClient("http://localhost:1234"); 
 client.IgnoreResponseStatusCode = true;
 client.Timeout = TimeSpan.FromSeconds(1);
 var req = new RestRequest("/body", Method.PUT);
 req.AddHeader("Content-Type","application/x-www-form-urlencoded");
 req.AddParameter("name","john", ParameterType.RequestBody);
 var res = client.Execute(req).Result;
```
In the screenshot you'll see that the form looks like "john=john" and the raw body is "john".

Using Postman the Form and Body is "name=john" as expected

![screen shot 2016-05-20 at 20 27 13](https://cloud.githubusercontent.com/assets/105126/15439638/5d567c1e-1ec9-11e6-9fe3-53ed50ee3b27.png)

**Comment by fubar-coder** [comment]
You have to use GetOrPost as parameter type.

**Comment by fubar-coder** [comment]
And you have to use POST. Using PUT does seem unusual for form-url-encoded

**Comment by jchannon** [comment]
Ah I've spotted it. Using GetOrPost on a PUT it doesn't add the ContentType header

**Comment by jchannon** [comment]
Using PUT and RequestBody it defaults to application/json

**Comment by jchannon** [comment]
Seems that it should add the header of `application/x-www-form-urlencoded` like it does for POST when using PUT

**Comment by fubar-coder** [comment]
It's some kind of tough. `application/x-www-form-urlencoded` is very unusual for `PUT` requests, because those are usually for storing data (see [What's the difference between a POST and a PUT HTTP REQUEST?](http://stackoverflow.com/questions/107390/whats-the-difference-between-a-post-and-a-put-http-request)). I agree, that there should be a way to support `application/x-www-form-urlencoded` together with `PUT`. Please let me validate some things first.

**Comment by jchannon** [comment]
Ok thanks.

I'll check with a colleague but I think they are using PUT on a 3rd party
API that has this requirement.

If it helps Restsharp seems to work. They spotted it when it didn't work
the same with Portable

**Comment by fubar-coder** [comment]
I released a new alpha version. Please close this issue when the request works as expected.

**Comment by jchannon** [comment]
Where can I see it?

**Comment by fubar-coder** [comment]
You can find the nuget feed on the myget gallery page: https://www.myget.org/gallery/restsharp-portable

**Comment by jchannon** [comment]
Thanks

**Comment by jchannon** [comment]
I get an error when adding it `'FubarCoder.RestSharp.Portable.Core' already
has a dependency defined for 'NETStandard.Library'.`

**Comment by fubar-coder** [comment]
It's a known problem. You have to use NuGet 3.5 beta (also for Visual Studio 2015 as VSIX). You can download it from https://dot.net download section

**Comment by jchannon** [comment]
Updated but now it doesn't compile:
![capture](https://cloud.githubusercontent.com/assets/105126/15465061/8b795dd4-20ca-11e6-8f92-877efc5f4882.PNG)

**Comment by fubar-coder** [comment]
This works here. It seems that you forgot a `dotnet restore` (when using .NET Core), or maybe nuget didn't add the `FubarCoder.RestSharp.Portable.Core` to your project and/or `packages.config`.

Example application (using both .NET Core and .NET Framework 4.6.1)
[TestRestSharpPortableCore.zip](https://github.com/FubarDevelopment/restsharp.portable/files/277135/TestRestSharpPortableCore.zip)

**Comment by jchannon** [comment]
Looks like nuget messed it up, readded the reference and now works as expected with PUT and GetOrPost
