### ISSUE TITLE
System.MissingFieldException: Field 'RestSharp.Portable.HttpClient.RestClient/<Execute>d__6`1<T_REF>.<>4__this' not found.

### ISSUE THREAD

**Issue by kartikbb** [FubarDevelopment/restsharp.portable#70]
I have the latest version of restshap portable and restsharp portable httpclient installed in Xamarin Forms PCL app. When i make http post request to my API, the library throws an exception -

"System.MissingFieldException: Field 'RestSharp.Portable.HttpClient.RestClient/<Execute>d__6`1<T_REF>.<>4__this' not found."

I have cleaned and rebuild the solution multiple times. But every time i run it in the iOS emulator, i get same error.

**Comment by fubar-coder** [comment]
Please ensure that you have the rest sharp portable httpclient library installed for your start project (main app project). When you still have problems, then you can send me this project and I'll take a look.

**Comment by kartikbb** [comment]
OK so your recommended fix did not do the trick.

**Comment by fubar-coder** [comment]
Ok, maybe you can create a small example application and upload it here? That would help me finding the issue.

**Comment by fubar-coder** [comment]
Closed due to inactivity

**Comment by rdesj** [comment]
I am getting this same issue, but I do not see any fix.  I have the latest portable, but I am getting this error:
RestSharp.Portable.HttpClient.RestClient/<Execute>d__6`1<T_REF>.<>4__this' not found

**Comment by fubar-coder** [comment]
Can you provide an example application and can you tell me something about your used environment? Do you use Xamarin Studio, Visual Studio, Windows, Linux, Mac OS, do you target Windows, iOS or Android? What version do you use for your development environment and for the library?

**Comment by rdesj** [comment]
I am using Visual Studio 2015 with Xamarin.  I have a portable base and an IOS and Droid applications.

I was originally implementing the HTTP request in the portable base and it was working for droid and had no errors with IOS.  Recently, I started getting the described errors.  I, just moved the implementation to the IOS and droid application and passing the classes to the portable base (dependency injection) and this fixed this issue.  I no longer am getting this.

HOWEVER,  When testing IOS with a Mac simulator, It seems to NOT be awaiting the async task as it should be.  I am going to be trouble shooting this today, but if you have any insights into why the await is not awaiting, that would be GREAT.

FYI… It is not an issue with restsharp, it is an issue with AWAITING async tasks…. I get the same issue using system.net.httpclient directly as well

**Comment by fubar-coder** [comment]
Regarding the `await` not working as expected, this usually happens when you're using the HttpClient from a non-async root function (e.g. like a non-async event handler or initialization function). You have two options:

1. Maybe using the [ModernHttpClient](https://github.com/paulcbetts/ModernHttpClient) fixes this problem
2. Change the problematic function to async

Here's a small example that shows how to use a custom HttpMessageHandler: 
[UseCustomHttpMessageHandler.zip](https://github.com/FubarDevelopment/restsharp.portable/files/331989/UseCustomHttpMessageHandler.zip)
