### ISSUE TITLE
Query String Encoding for '+' on Get request

### ISSUE THREAD

**Issue by MarcMenghin** [FubarDevelopment/restsharp.portable#73]
I try to pass a date as a query string but the + sign for the offset gets lost (as it represents a space). So it is not escaped to '%2B' but if I replace it manually the '%' sign gets replaced by the correct '%25'. 

My date string is created using the 'O' format (e.g: `DateTime.Now.ToString('O');`) and added using `request.AddQueryParameter(..)`. 

I'm using the `RestSharp.Portable.WebRequest.RestClient`implementation.

**Comment by fubar-coder** [comment]
Fixed in 4.0
