### ISSUE TITLE
ServicePointManager.ServerCertificateValidationCallback alternative

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#74]
Hi

In the `netstandard` package is there an API that allows for SSL validation callback?

**Comment by fubar-coder** [comment]
It's as far as I know available in the HttpMessageHandler. To use this feature, you have to use the HttpClient implementation.

**Comment by jchannon** [comment]
How do I use that?

**Comment by jchannon** [comment]
Can't see anything here
https://dotnet.github.io/api/System.Net.Http.HttpMessageHandler.html

**Comment by fubar-coder** [comment]
It's called `ServerCertificateCustomValidationCallback` and is in version 4.1 (not released yet) of the `System.Net.Http` package, but you can - on Windows - use the `System.Net.Http.WinHttpHandler` from the same named package. I'll hack together a small example application, which utilizes the .NET core tool chain, but targets net46.

**Comment by jchannon** [comment]
I looked at HttpClientHandler and the docs say its there but its not when you do `new HttpClientHandler()` I think what has to be done is add a certificate to the store as it works differently per OS

**Comment by fubar-coder** [comment]
Yes, this would be the best option. Regarding the missing property: Only 4.0 is available via nuget. 4.1 will (probably) be part of the next .NET Core.

**Comment by jchannon** [comment]
What do you mean by v4?

I'm talking about https://dotnet.github.io/api/System.Net.Http.HttpClientHandler.html#System_Net_Http_HttpClientHandler_ServerCertificateCustomValidationCallback which although documented actually isnt available for some reason

**Comment by fubar-coder** [comment]
The documentation already includes the API for System.Net.Http 4.1, while only 4.0 is released on nuget.org.

**Comment by jchannon** [comment]
Yup, just seen this https://github.com/dotnet/corefx/commit/97c940eec1f6afe3e4af31e72d79c3a11e7b1ff1

**Comment by jchannon** [comment]
4.1 is now out, what would be the best way to use the HttpClientHandler with Restsharp.Portable/
