### ISSUE TITLE
Process streamed results

### ISSUE THREAD

**Issue by jchannon** [FubarDevelopment/restsharp.portable#76]
Hi,

We have some code here https://github.com/VQComms/ReDock/blob/master/Src/ReDock/DockerClient.cs#L35-L53 in Restsharp that deals with a streaming response.  After looking at the Restsharp.Portable API I can't see anything similar. Maybe I'm missing it?

Thanks

**Comment by fubar-coder** [comment]
It's not implemented, but something similar should be possible
