### ISSUE TITLE
How remove Header "Expect", from request?

### ISSUE THREAD

**Issue by Nightw0rk** [FubarDevelopment/restsharp.portable#77]
Hi. today a getting trouble with POST request over proxy squid/3.1.19

> Invalid Request error was encountered while trying to process the request:
> 
> POST /desktop/login?key=TESTTESTTESTTEST HTTP/1.1
> Accept: application/json, text/json, text/x-json, text/javascript, application/xml, text/xml
> User-Agent: RestSharp/3.3.0
> Proxy-Authorization: Basic blahlblah=)
> Content-Type: application/json; charset=utf-8
> Host: remotehost
> Content-Length: 114
> Expect: 100-continue
> Accept-Encoding: gzip, deflate
> Proxy-Connection: Keep-Alive
> 
> Some possible problems are:
> •Missing or unknown request method.
> •Missing URL.
> •Missing HTTP Identifier (HTTP/1.0).
> •Request is too large.
> •Content-Length missing for POST or PUT requests.
> •Illegal character in hostname; underscores are not allowed.
> •HTTP/1.1 «Expect:» feature is being asked from an HTTP/1.0 software.

I think problem at header Expect.

**Comment by fubar-coder** [comment]
That's a known problem. You have to create a custom `IHttpClientFactory` (derived from `DefaultHttpClientFactory`). The `Expect` HTTP header can be disabled (probably, depending on your framework and framework version):

- Globally `System.Net.ServicePointManager.Expect100Continue`
- Using `HttpClient`: Modifying the `DefaultRequestHeaders` of the `HttpClient`
- Using `WebRequest`: Modifying `ServicePoint.Expect100Continue` of the `HttpWebRequest`

I leave this ticket open as a reminder for me to disable the `Expect100Continue` by default.

**Comment by fubar-coder** [comment]
According to [http://wiki.squid-cache.org/Features/HTTP11], this seems to be a problem in Squid 3.1. The workarounds above should be sufficient for this use case.
