### ISSUE TITLE
`System.Net.IWebProxy` defined for all WebRequest PCL versions, preventing compilation due to type redefinition (tested on PCL profile 259)

### ISSUE THREAD

**Issue by ggirard07** [FubarDevelopment/restsharp.portable#79]
**Steps to reproduce**
1. Create a new PCL project
2. Configure it due match profile 259 (.Net Framework 4.5, Windows 8, Windows Phone Silverlight 8, ASP.Net Core 1.0, Windows Phone 8.1, Xamarin.Android, Xamarin.iOS, Xamarin.iOS (Classic)).
3. Add Nuget depencies for `FubarCoder.RestSharp.Portable.WebRequest`
4. Add some code to consume the NuGets and build

**Expected result**
Build should happen properly

**Actual result**
VS2015 is unable to compile the solution
> The type 'IWebProxy' exists in both 'RestSharp.Portable.WebRequest, Version=3.3.0.0, Culture=neutral, PublicKeyToken=be81bb0f53eab22f' and 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'

**Remarks**
Currently it looks like the type `IWebProxy` is simply proxied on a few platform (like on Android [HERE ](https://github.com/FubarDevelopment/restsharp.portable/blob/master/RestSharp.Portable.WebRequest.Android/RestSharp.Portable.WebRequest.Android.csproj#L70) and [HERE](https://github.com/FubarDevelopment/restsharp.portable/blob/master/System.Net.Http.Primitives.Redirect/Redirects.cs#L4)), where as for the PCL projects (PCL and AsyncPCL) the type is fully redefined instead in the `System.Net` namespace ([HERE](https://github.com/FubarDevelopment/restsharp.portable/blob/master/RestSharp.Portable.WebRequest.AsyncPCL/RestSharp.Portable.WebRequest.AsyncPCL.csproj#L80), [HERE ](https://github.com/FubarDevelopment/restsharp.portable/blob/master/RestSharp.Portable.WebRequest.PCL/RestSharp.Portable.WebRequest.PCL.csproj#L102) and [HERE](https://github.com/FubarDevelopment/restsharp.portable/blob/master/System.Net.Http.Primitives/IWebProxy.cs))
This make the WebRequesr NuGet unusable for PCLs already defining the `IWebProxy` type.

**Comment by fubar-coder** [comment]
You must add `FubarCoder.RestSharp.Portable.WebRequest` to your main project. It uses the `bait-and-switch` technique, which uses a version of this library that's compiled for you target framework (e.g. Xamarin.Android). This version contains a type forward to the correct version.

**Comment by ggirard07** [comment]
Tried as yous said, with same result.
You can find a reproduction sample [here](https://github.com/ggirard07/RestSharpPortable.WebRequestTest).

Issue is happening to me with profile 259 which requires NuGet `Microsoft.Net.Http`, but also with profile 111 which does not require any additional NuGet to reproduce.

**Comment by ggirard07** [comment]
@fubar-coder did you have a chance to look at my latest reply?

**Comment by fubar-coder** [comment]
4.0 is released and it doesn't contain a IWebProxy any more for PCLs. The recommended way is to use dependency injection when you want a `IRestClient` which should have a `Proxy` property for all platforms that support it.
