### ISSUE TITLE
NullReferenceException with Method.PUT

### ISSUE THREAD

**Issue by boodoolak** [FubarDevelopment/restsharp.portable#84]
Please, help me with this question http://stackoverflow.com/questions/39036762/how-can-i-find-why-restsharp-put-throw-exception
Moderators mark question as dublicate but it not dublicate.

**Comment by fubar-coder** [comment]
I'm currently on vacation and don't have access to a PC. I'll take a look at it in ca. one week.

**Comment by boodoolak** [comment]
Thank you, i'll wait.

**Comment by nEVIL2142** [comment]
Hello, did you resolve this issue?

**Comment by nEVIL2142** [comment]
I can't send PUT.

**Comment by nEVIL2142** [comment]
@fubar-coder
