### ISSUE TITLE
Problem with Xamarin.Forms and UWP

### ISSUE THREAD

**Issue by raminmjj** [FubarDevelopment/restsharp.portable#88]
there is no problem with android project.
but UWP project throw below exception.

> Could not load file or assembly 'System.Net.Http.Primitives, Version=1.5.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.

how to fix it?

**Comment by fubar-coder** [comment]
You have two options: Wait for the 4.0 release or use a binding redirect (which nuget should've created automatically in your app.config).

**Comment by fubar-coder** [comment]
4.0 is released
