### ISSUE TITLE
The binary is built in debug mode uwp store.

### ISSUE THREAD

**Issue by nEVIL2142** [FubarDevelopment/restsharp.portable#90]
Hello, i can't push mt UWP app in store, all this packages i downloaded via nuget links on main.
![iu0yrnx](https://cloud.githubusercontent.com/assets/5916144/20126915/14cf4b58-a66c-11e6-9c1c-2074678673a4.png)

**Comment by fubar-coder** [comment]
Please try version 4.0.7 as soon as it's built and published (within an hour)
