### ISSUE TITLE
System.FormatException when trying to use RestRequest.AddParameter.

### ISSUE THREAD

**Issue by kinju4374** [FubarDevelopment/restsharp.portable#94]
I am trying to add a parameter in request body but getting Format Exception

`RestRequest request = new RestRequest(Method.POST);`
`request.AddParameter("Test", mybytearray, ParameterType.RequestBody);`
`response = await client.Execute(request);`

Can you suggest why it is not working? In old version, this was working fine as expected.

**Comment by fubar-coder** [comment]
The body parameter is special, because it has no name, so the name is used as `Content-Type`, which in your case is `Test` which isn't allowed. You have two choices:

* Pass `null` instead of `Test` and the sent content type will become `application/octet-stream`
* Pass the content type instead of `Test` (e.g. `application/octet-stream`)

**Comment by kinju4374** [comment]
@fubar-coder  Thanks for quick response. It works perfect now.

**Comment by kinju4374** [comment]
@fubar-coder  I have one doubt when a request is sent to the server and in between internet connectivity is not available for receiving a response, does this API tries to send the same request again automatically?

**Comment by fubar-coder** [comment]
No, it doesn't perform retransmission. That is something that has to be handled by the underlying infrastructure (i.e. HttpWebRequest, or the HttpClient message handler like e.g. HttpClientHandler, WebRequestHandler, etc...) or by the client application.

**Comment by kinju4374** [comment]
OK, Thanks. I just confirmed because my client when accessing the app via 3G/4G network in low network areas were receiving two same requests one after the another.
