### ISSUE TITLE
Where is RestClient?

### ISSUE THREAD

**Issue by im1dermike** [FubarDevelopment/restsharp.portable#96]
I installed `FubarCoder.RestSharp.Portable.Core` into my .netstandard project.  After importing the `RestSharp.Portable` namespace, I have access to the `RestRequest` object, but I can't figure out how to import the namespace for `RestClient`.

**Comment by fubar-coder** [comment]
You need the implementation package too. Either [FubarCoder.RestSharp.Portable.HttpClient](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.HttpClient/) or [FubarCoder.RestSharp.Portable.WebRequest](https://www.nuget.org/packages/FubarCoder.RestSharp.Portable.WebRequest/). Be aware that those packages don't support all features on netstandard1.1. You should use the implementation packages in a project targeting netcoreapp1.x, net4x, or xamarin android/ios and only use the `IRestClient` interface in the PCL or netstandard projects.
