### ISSUE TITLE
Timeout while getting response from the server

### ISSUE THREAD

**Issue by kinju4374** [FubarDevelopment/restsharp.portable#97]
I am facing an issue, when our server takes more than 1-2 minutes to send a response, the request automatically times out. Can we add a timeout for this scenario, so at least I get a response? Right now, due to time-out response becomes null.

**Comment by kinju4374** [comment]
This solved my problem
`client.Timeout = TimeSpan.FromMinutes(5);`

where client is RestClient.

**Comment by fubar-coder** [comment]
The timeout of 5 minutes is applied to the client, which means that it applies to all requests. When your request takes less time, then it will finish before the timeout.

**Comment by kinju4374** [comment]
Is there any default timeout set for RestClient? If I don't mention timeout, what will it consider?

**Comment by fubar-coder** [comment]
It's the default timeout of the underlying request engine (either HttpClient or HttpWebRequest) and is (IMHO) 60 seconds.

**Comment by kinju4374** [comment]
Ok thanks
